Fix Paginate(Keys()) max width (#1)
when running the bellow query in a database that contains many keys, it
results in a bad request

```
> Paginate(Keys(), {size: 10})
Error: bad request
{
  errors: [
    {
      code: 'bad request',
      description: 'Query exceeds max width. Max: 100000, current: 118986.'
    }
  ]
}
```

even the `size` parameter is being ignored.

Turns out the Union of the indexes is not necessary as
`DocumentsByCollection` will return all keys anyway.